package uz.bayroq

data class Country(val code: String, val name: String) {
    val flag: String = code.map { String(Character.toChars(0x1F1E6 + (it - 'A'))) }.joinToString("")
}

val COUNTRIES = listOf(
    Country("UZ", "O'zbekiston"), Country("US", "AQSh"), Country("RU", "Rossiya"),
    Country("TR", "Turkiya"), Country("GB", "Buyuk Britaniya"), Country("DE", "Germaniya"),
    Country("FR", "Fransiya"), Country("JP", "Yaponiya"), Country("KR", "Janubiy Koreya"),
    Country("CN", "Xitoy"), Country("IT", "Italiya"), Country("ES", "Ispaniya"),
    Country("BR", "Braziliya"), Country("AR", "Argentina"), Country("CA", "Kanada"),
    Country("IN", "Hindiston"), Country("EG", "Misr"), Country("SA", "Saudiya Arabistoni"),
    Country("AE", "BAA"), Country("KZ", "Qozog'iston"), Country("KG", "Qirg'iziston"),
    Country("TJ", "Tojikiston"), Country("TM", "Turkmaniston"), Country("AZ", "Ozarbayjon"),
    Country("UA", "Ukraina"), Country("PL", "Polsha"), Country("NL", "Niderlandiya"),
    Country("SE", "Shvetsiya"), Country("CH", "Shveytsariya"), Country("AU", "Avstraliya"),
    Country("MX", "Meksika"), Country("PT", "Portugaliya"), Country("GR", "Gretsiya"),
    Country("ID", "Indoneziya"), Country("MY", "Malayziya"),
    Country("AF", "Afg'oniston"),
    Country("AL", "Albaniya"),
    Country("DZ", "Jazoir"),
    Country("AD", "Andorra"),
    Country("AO", "Angola"),
    Country("AM", "Armaniston"),
    Country("AT", "Avstriya"),
    Country("BH", "Bahrayn"),
    Country("BD", "Bangladesh"),
    Country("BY", "Belarus"),
    Country("BE", "Belgiya"),
    Country("BZ", "Beliz"),
    Country("BJ", "Benin"),
    Country("BT", "Butan"),
    Country("BO", "Boliviya"),
    Country("BA", "Bosniya va Gersegovina"),
    Country("BW", "Botsvana"),
    Country("BN", "Bruney"),
    Country("BG", "Bolgariya"),
    Country("BF", "Burkina-Faso"),
    Country("BI", "Burundi"),
    Country("KH", "Kambodja"),
    Country("CM", "Kamerun"),
    Country("CV", "Kabo-Verde"),
    Country("CF", "Markaziy Afrika Respublikasi"),
    Country("TD", "Chad"),
    Country("CL", "Chili"),
    Country("CO", "Kolumbiya"),
    Country("KM", "Komor orollari"),
    Country("CG", "Kongo Respublikasi"),
    Country("CD", "Kongo Demokratik Respublikasi"),
    Country("CR", "Kosta-Rika"),
    Country("HR", "Xorvatiya"),
    Country("CU", "Kuba"),
    Country("CY", "Kipr"),
    Country("CZ", "Chexiya"),
    Country("DK", "Daniya"),
    Country("DJ", "Jibuti"),
    Country("DM", "Dominika"),
    Country("DO", "Dominikan Respublikasi"),
    Country("EC", "Ekvador"),
    Country("SV", "Salvador"),
    Country("GQ", "Ekvatorial Gvineya"),
    Country("ER", "Eritreya"),
    Country("EE", "Estoniya"),
    Country("SZ", "Esvatini"),
    Country("ET", "Efiopiya"),
    Country("FJ", "Fiji"),
    Country("FI", "Finlyandiya"),
    Country("GA", "Gabon"),
    Country("GM", "Gambiya"),
    Country("GE", "Gruziya"),
    Country("GH", "Gana"),
    Country("GD", "Grenada"),
    Country("GT", "Gvatemala"),
    Country("GN", "Gvineya"),
    Country("GW", "Gvineya-Bisau"),
    Country("GY", "Gayana"),
    Country("HT", "Gaiti"),
    Country("HN", "Gonduras"),
    Country("HU", "Vengriya"),
    Country("IS", "Islandiya"),
    Country("IR", "Eron"),
    Country("IQ", "Iroq"),
    Country("IE", "Irlandiya"),
    Country("JM", "Yamayka")
)
